src/react/components/KeyGeneratioinFlow/0-KeyInputs.tsx, src/react/components/MnemonicGenerationFlow/0-GenerateMnemonic.tsx, src/react/components/MnemonicGenerationFlow/1-2-ShowMnemonic.tsx, src/react/components/MnemonicGenerationFlow/3-VerifyMnemonic.tsx, src/react/constants.ts, src/react/pages/Home.tsx, src/react/pages/MnemonicGenerationWizard.tsx, src/react/pages/MnemonicImport.tsx
Changed all instances of "mnemonic" to "Secret Recovery Phrase". Did not rename any tag names, functions etc... (can be, and probably should be done in the future). Also did not change any on the CLI, only the GUI. Hyperlink color should be changed for greater legibility.
=> Fixes for Issue #16 & 17

src/react/components/KeyConfigurationWizard.tsx, src/react/components/KeyGeneratioinFlow/0-KeyInputs.tsx, src/react/components/KeyGeneratioinFlow/1-VerifyKeysPassword.tsx, src/react/components/KeyGeneratioinFlow/2-SelectFolder.tsx, src/react/components/MnemonicGenerationFlow/0-GenerateMnemonic.tsx, src/react/components/MnemonicGenerationFlow/1-2-ShowMnemonic.tsx, src/react/components/MnemonicGenerationFlow/3-VerifyMnemonic.tsx, src/react/components/MnemonicGenerationWizard.tsx, src/react/components/MnemonicImport.tsx, src/react/components/NetworkPicker.tsx, src/react/components/StepNavigation.tsx, src/react/pages/Home.tsx
Fixes #4 
@colfax23 There's a small UI change in the Network Picker.  I swapped the div-button for a regular button.  Let me know if you want me to style it like it was (more padding).  The background color on hover is now that of other buttons, but let me know if you want to go back to green.
=> Support keyboard navigation

package-lock.json, package.json, src/react/components/MnemonicGenerationFlow/1-2-ShowMnemonic.tsx, yarn.lock
Not shown in the picture, but when you click on the copy icon, the tooltip text updates to "Copied".  I played with the "Snackbar" component in Material-UI, but it seemed a bit much.  I had to install `@material-ui/lab` for the Alert component.  I used `yarn add @material-ui/lab`, and there was just a simple update to yarn.lock.  I then ran `npm install` so that package-lock.json got updated, and then there were many changes to both lock files.  Not sure what the right move is here.  I haven't used yarn a lot and don't know how best to keep these lock files in sync.
=> UX changes to mnemonic generation step

README.md
Updated the read me to include
- Environment set up & dependencies
- how to run diagnostics
=> Updated read me and styles

README.md
=> Add instructions to set a basic development environment on Windows

src/react/commands/Eth2Deposit.ts, src/react/components/KeyGenerationWizard.tsx, src/react/components/MnemonicGenerationWizard.tsx
Remove some weird behavior with setTimeout usage, made calling eth2deposit_proxy async and clean up some of those usage. Errors will now bubble up and can be handled in the UI. UI does not hang anymore when calling eth2deposit_proxy.
=> Remove setTimeout usage and improve promise code with child_process

src/react/components/MnemonicGenerationFlow/1-2-ShowMnemonic.tsx, src/react/components/MnemonicGenerationFlow/3-VerifyMnemonic.tsx, src/react/components/MnemonicGenerationWizard.tsx, src/react/components/NetworkPicker.tsx, src/react/pages/MainWizard.tsx
When running on mainnet, disable copy mnemonic and make the user type word by word.
=> Mnemonic verify word by word for mainnet

src/react/commands/Eth2Deposit.ts, src/react/components/KeyGenerationWizard.tsx, src/react/components/MnemonicGenerationFlow/0-GenerateMnemonic.tsx, src/react/components/MnemonicGenerationWizard.tsx, src/scripts/eth2deposit_proxy.py
=> Raise and display errors from eth2deposit cli to UI

src/react/components/MnemonicImport.tsx, src/react/components/MnemonicImportFlow/1-ValidatingMnemonic.tsx
=> Add spinner during mnemonic validation

src/react/commands/Eth2Deposit.ts
Should fix most of our CLI calling issues with spaces. Tested to work correctly on Windows and Linux.
It should also be slightly faster for calling the CLI since execFile does not need to create a shell first.
=> Refactor Eth2Deposit.ts, replace exec with execFile to avoid escaping issues and space issues in CLI

src/electron/index.ts, src/react/components/KeyGeneratioinFlow/2-SelectFolder.tsx
=> Remove remote module usage for dialogs

src/react/components/MnemonicGenerationFlow/1-2-ShowMnemonic.tsx
=> Gray -> white mnemonic words

src/electron/index.ts, src/react/components/KeyConfigurationWizard.tsx, src/react/components/KeyGenerationWizard.tsx, src/react/components/MnemonicGenerationFlow/3-VerifyMnemonic.tsx, src/react/components/MnemonicGenerationWizard.tsx
I removed the informative log messages, as they will be on the client and wont be useful.  I left some specific error log messages that can be used while debugging remotely..
=> Update log messages

src/react/commands/BashUtils.ts, src/react/components/KeyGeneratioinFlow/4-KeysCreated.tsx
=> Make finished folder clickable and open keystore in file manager

src/react/components/MnemonicGenerationFlow/0-GenerateMnemonic.tsx, src/react/pages/Home.tsx
=> Reworked links

src/react/components/KeyGeneratioinFlow/4-KeysCreated.tsx
=> add note about clearing clipboard

src/react/components/MnemonicGenerationFlow/3-VerifyMnemonic.tsx
=> Added spacebar, backspace, and arrowkey navigation to textfield

package.json, src/electron/preload.ts, src/electron/renderer.d.ts, src/react/components/KeyConfigurationWizard.tsx, src/react/components/KeyGenerationWizard.tsx, src/react/constants.ts, yarn.lock
=> Address checksum integration with web3js

.gitignore, README.md, src/electron/Eth2Deposit.ts, src/electron/preload.ts, src/electron/renderer.d.ts, src/react/App.tsx, src/react/components/BTECConfigurationWizard.tsx, src/react/components/BTECGenerationFlow/0-MainInputs.tsx, src/react/components/BTECGenerationFlow/1-ValidatingBLSCredentials.tsx, src/react/components/BTECGenerationFlow/2-SelectFolder.tsx, src/react/components/BTECGenerationFlow/3-CreatingBTECFile.tsx, src/react/components/BTECGenerationFlow/4-BTECFileCreated.tsx, src/react/components/BTECGenerationWizard.tsx, src/react/components/FinishBTEC.tsx, src/react/components/MnemonicGenerationFlow/1-2-ShowMnemonic.tsx, src/react/components/ReuseMnemonicActionPicker.tsx, src/react/constants.ts, src/react/pages/Home.tsx, src/react/pages/MainWizard.tsx, src/react/types.ts, src/scripts/bundle_proxy_linux.sh, src/scripts/bundle_proxy_win.bat, src/scripts/stakingdeposit_proxy.py
This PR adds BLS to execution change (BTEC) flow to Wagyu Key Gen. It starts by clicking on the *Use existing secret recovery phrase* button. It fixes or improve some minor stuff too.
=> Adding BLS to execution change flow

src/react/components/MnemonicImport.tsx
=> trim imported mnemonic secret phrase

src/react/components/MnemonicImport.tsx
Remove punctuations and potential double spaces
=> Clean mnemonic when importing

src/react/components/MnemonicImport.tsx
=> Fix aggressive trimming issue

src/react/App.tsx, src/react/components/OnlineDetector.tsx, src/react/constants.ts
User had a good suggestion to provide a connectivity detection and warning the user: #172 
Adding a listener and using `navigator.onLine` to detect connection while using MUI Snackbar with Alert to display a warning to the user if a connection is detected.
Two UX constraint I added:
- Added the detection in `App.tsx` so it will exist outside of only the landing component
- Not being able to dismiss the alert message except through clicking the snackbar action. Closing by clicking away would probably defeat the purpose due to the severity of the security concern.
This can be tested by toggling your wifi connection while the app is open.
=> Adding connection detector to alert the user if they are online

.github/release_template.md
=> Add AppArmor documentation
